1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]
2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]

3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

4.	Python program to get the sum of every cubed value and its previous integer. 

5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]

6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]

8.	Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


### Problem 1

In [8]:
import os
import hashlib
path = 'D:\\New1'
hashes = []
for (dirpath, dirs, files) in os.walk(path):
    for file in files:
        try:
            filepath = os.path.join(dirpath, file)
            file = open(filepath, 'r')
            content = file.read()
            file.close()
            message = hashlib.sha256(content.encode())
            h = message.hexdigest()
            if h not in hashes:
                hashes.append(h)
            else:
                os.remove(filepath)
                print('Removed duplicate:', filepath)
        except Exception as e:
            print(e)

Removed duplicate: D:\New1\duplis\test.txt
Removed duplicate: D:\New1\duplis\test2.txt


###  Problem 2

In [23]:
import random
import string
pwlen = 6
lower = random.sample('abcdefghijklmnopqrstuvwxyz',2)
upper = random.sample('ABCDEFGHIJKLMNOPQRSTUVWXYZ',1)
digits = random.sample('1234567890',2)
spec = random.sample(list(string.punctuation), pwlen-2-1-2)
pw = random.sample(lower+upper+digits+spec, 6)
pw=''.join(pw)
pw

'5W@3fh'

### Problem 3

In [49]:
import numpy as np
arr = np.array(range(12)).reshape(3,4)
idx=0

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        flag=0
        for k in range(1,(idx//2)+1):
            if idx%k==0:
                flag+=1
        if flag==1:
            arr[i, j]=arr[i,j]**3
        idx+=1
arr

array([[   0,    1,    8,   27],
       [   4,  125,    6,  343],
       [   8,    9,   10, 1331]])

### Problem 4

In [53]:
import numpy as np
arr = np.array(range(12)).reshape(3,4)
idx=0

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        flag=0
        for k in range(1,(idx//2)+1):
            if idx%k==0:
                flag+=1
        if flag==1:
            if j!=0:
                arr[i, j]=arr[i,j]**3+arr[i,j-1]
            else:
                arr[i, j]=arr[i,j]**3+arr[i-1,-1]
        idx+=1
arr

array([[   0,    1,    9,   36],
       [   4,  129,    6,  349],
       [   8,    9,   10, 1341]])

###  Problem 5

In [34]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
set(arr1).intersection(arr2)

{3, 4, 5}

### Problem 6

In [36]:
li = [7*i for i in range(1,(7*7)+1)]
arr7 = np.array(li).reshape(7,7)
arr7[-1][-1]

343

### Problem 7

In [54]:
shape = (5,5)
mat = np.zeros(shape)
mat[::2, ::2] = 1
mat[1::2, 1::2] = 1
mat

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

### Problem 8

In [51]:
li = ['A','B','C','D','E','F','G','H','I','a','K','L','M','N','o','P','Q','R','S','T','U','0','W','O']

ct=0
for i in range(len(li)):
    if li[i].lower() in 'aeiou':
        li[i] = np.nan
        ct+=1
print('Vowel count:',ct)
mat = np.array(li)
mat

Vowel count: 7


array(['nan', 'B', 'C', 'D', 'nan', 'F', 'G', 'H', 'nan', 'nan', 'K', 'L',
       'M', 'N', 'nan', 'P', 'Q', 'R', 'S', 'T', 'nan', '0', 'W', 'nan'],
      dtype='<U32')